name: Cypress Tests

on:
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          record: true
        env:
         CYPRESS_record_key: ${{ secrets.Cypress_RECORD_KEY }}
         CYPRESS_projectId: ${{ secrets.Cypress_PROJECTID }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
        working-directory: cypress
      - name: Run cypress test
        run: npx cypress run
        env:
         CYPRESS_record_key: ${{ secrets.Cypress_RECORD_KEY }}
         CYPRESS_projectId: ${{ secrets.Cypress_PROJECTID }}
